# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔
live2d:
  enable: true
  scriptFrom: local  
  model:
    use: live2d-widget-model-wanko    //妹子有很多个，叫名字他才出来
  display:    
    position: right   //位置
    width: 150    //妹子宽度
    height: 300    //妹子高度
  mobile:
    show: true
    
# SubNav
subnav:
  github: "#"
  zhihu: "#"
  # douban: "#"
  #mail: "#"
  facebook: "#"
  google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# Miscellaneous
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: https://ts2.cn.mm.bing.net/th?id=ODLS.a3ec9c98-6c94-42e9-b3fc-7010ee8fbc10&w=16&h=16&o=6&pid=1.2
#是否开启分享
share_jia: true
share_addthis: false
#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
duoshuo: true
#是否开启云标签
tagcloud: true

#是否开启友情链接
#不开启——
friends: false
#开启——
# friends:
#   奥巴马的博客: http://localhost:4000/
#   卡卡的美丽传说: http://localhost:4000/
#   本泽马的博客: http://localhost:4000/
#   吉格斯的博客: http://localhost:4000/
#   习大大大不同: http://localhost:4000/
#   托蒂的博客: http://localhost:4000/

#是否开启“关于我”。
#不开启——
#aboutme: false
#开启——
aboutme: 爱玩游戏，能找到该做的事，希望时间不要白白流逝。
